### ISSUE TITLE
Running the AOTMachine in a JMH test throws `java.lang.IllegalArgumentException: array is not of length 1`

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#512]
Attempting to run [this benchmark](https://github.com/shaunsmith/wasm-bench) with the AOT result in:

```
com.dylibso.chicory.runtime.exceptions.WASMRuntimeException: An underlying Java exception occurred
        at com.dylibso.chicory.aot.AotMachine.call(AotMachine.java:362)
        at com.dylibso.chicory.runtime.Instance.lambda$export$2(Instance.java:231)
        at org.graalvm.benchmark.ChicoryAotTest.chicoryAotTest(ChicoryAotTest.java:82)
        at org.graalvm.benchmark.jmh_generated.ChicoryAotTest_chicoryAotTest_jmhTest.chicoryAotTest_avgt_jmhStub(ChicoryAotTest_chicoryAotTest_jmhTest.java:197)
        at org.graalvm.benchmark.jmh_generated.ChicoryAotTest_chicoryAotTest_jmhTest.chicoryAotTest_AverageTime(ChicoryAotTest_chicoryAotTest_jmhTest.java:158)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:527)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:504)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: array is not of length 1
        at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:175)
        at java.base/java.lang.invoke.MethodHandleImpl.checkSpreadArgument(MethodHandleImpl.java:587)
        at com.dylibso.chicory.aot.AotMachine.call(AotMachine.java:353)
        ... 14 more
```

Although, the setup is similar to the one used in the `jmh` submodule in this repository.

**Comment by andreaTP** [comment]
Fixed here:
https://github.com/shaunsmith/wasm-bench/pull/1/commits/1df5a72f2f536da6b0eff8a3cb844f5acaf6e9af

We need some better error messages but is not "strictly" a bug ...
