### ISSUE TITLE
Check Android support in CI

### ISSUE THREAD

**Issue by andreaTP** [dylibso/chicory#535]
It would be great to verify that Chicory works in an Android application.

I just casually found a starting point for implementing this:
- found [here](https://github.com/mockk/mockk/blob/edf9f95ecfae314c22452a1776b074803ae4a42d/.github/workflows/gradle.yml#L87)
- and [this](https://github.com/AdamMc331/AndroidStudyGuide/tree/development) looks to be an easy way to get started

**Comment by yigit** [comment]
Hi,
So i took a look at this (totally random, found this project when i was looking into [mcp.run](https://docs.mcp.run/developing-a-servlet/) for some personal project ideas)

Unfortunately, because you are using maven, there is no easy way to set this up, because there is no official tooling for maven.
You are also using junit5, which is not officially supported for android instrumentation tests (but there is a [3rd party plugin](https://github.com/mannodermaus/android-junit5) ).

Here is what I've done:
* locally compile chicory 
   ` mvn deploy -DaltDeploymentRepository=local-repo::default::file:./local-repo`
* create a new android gradle project next to `chichory` checkout
   ```
    ➜  src ls |grep chicory
    chicory
    chicory-android
* included that repo in my project as a maven repository
   ```
   settings.gradle.kts
   maven {
       url = uri(settingsDir.resolve("../chicory/local-repo"))
   }
   ```
* converted `.class` files into a jar from `<chicory-root>/runtime/target/test-classes` and included in my android project
* run tests 

[chicory-android.zip](https://github.com/user-attachments/files/18354488/chicory-android.zip)

**Comment by yigit** [comment]
Hi,
So i took a look at this (totally random, found this project when i was looking into [mcp.run](https://docs.mcp.run/developing-a-servlet/) for some personal project ideas)

Unfortunately, because you are using maven, there is no easy way to set this up, because there is no official tooling for maven.
You are also using junit5, which is not officially supported for android instrumentation tests (but there is a [3rd party plugin](https://github.com/mannodermaus/android-junit5) ).

Here is what I've done:
* locally compile chicory 
   ` mvn deploy -DaltDeploymentRepository=local-repo::default::file:./local-repo`
* create a new android gradle project next to `chichory` checkout
   ```
    ➜  src ls |grep chicory
    chicory
    chicory-android // this is the android project zipped in attachments
* included that repo in my project as a maven repository
   ```
   settings.gradle.kts
   maven {
       url = uri(settingsDir.resolve("../chicory/local-repo"))
   }
   ```
* converted `.class` files into a jar from `<chicory-root>/runtime/target/test-classes` and included in my android project 
   lib/testclasses.jar
   ```
   // runtime-tests/build.gradle.kts
  androidTestImplementation(files("lib/testclasses.jar"))
  ```
* added runtime dependencies (these are declared in `gradle/libs.versions.toml`)
  ```
  androidTestImplementation(files("lib/testclasses.jar"))
  androidTestImplementation(libs.chicory.runtime) // these are loaded from the local maven repo built above
  androidTestImplementation(libs.chicory.wasm)
  androidTestImplementation(libs.chicory.wasmCorpus)
  ```
* run tests  [test results.zip](https://github.com/user-attachments/files/18354507/test.results.zip)
  `./gradlew runtime-tests:connectedCheck`
  Most are passing except 2 are failing, i think it is related to loading the wasm test files.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.io.InputStream.readAllBytes()' on a null object reference
at com.dylibso.chicory.wasm.Parser.readByteBuffer(Parser.java:104)
at com.dylibso.chicory.wasm.Parser.parse(Parser.java:244)
at com.dylibso.chicory.wasm.Parser.parse(Parser.java:236)
at com.dylibso.chicory.wasm.Parser.parse(Parser.java:223)
at com.dylibso.chicory.wasm.Parser.parse(Parser.java:196)
at com.dylibso.chicory.runtime.InterruptionTest.shouldInterruptCall(InterruptionTest.java:32)
at java.lang.reflect.Method.invoke(Native Method)
at java.util.ArrayList.forEach(ArrayList.java:1528)
at java.util.ArrayList.forEach(ArrayList.java:1528)
```

Attached is the project that you can unzip next to your checkout and should work after you build a local repo. (you can configure the repo location in the settings.gradle.kts file)

```
/gradlew runtime-tests:connectedCheck --info
```
Project zip:
[chicory-android.zip](https://github.com/user-attachments/files/18354510/chicory-android.zip)

---
I'm really not familiar with maven so this setup might be very sub-optimal, I just wanted to give it a shot after seeing this bug.
I wish you were using gradle and kotlin :). I think this project would be very interesting as a Kotlin Multiplatform project . You could support other platforms, including embedding this into ios apps. 
Since your impl is pure java, it should be relatively easy to convert to a pure kotlin.
**I understand that is not a reasonable request, so this is not a request :). Just a wish that I wanted to share**.


But if you can somehow setup your build to build jars for tests (or class files, it would be easy to create a gradle task to handle jar creation), it would be possible to add this to your CI to test it on Android runtime.

Hope this is helpful.

**Comment by andreaTP** [comment]
Hi @yigit !

Thanks a lot for your interest in this project!
Your exploration looks extremely useful, thanks for sharing, a few of considerations:

- having a separate `gradle` project to deal with Android has always been in the back of my mind, we do something similar even in [Java Gradle projects](https://github.com/microsoft/kiota-java/tree/main/components/abstractions/android), so, thumb up for this approach :+1: 
- "pure kotlin": I encourage you to check out [Chasm](https://github.com/CharlieTap/chasm) as it might be aligned with your idea. In Chicory, Android support is a "desired side effect" of building on pure Java 11, not a primary goal.
- `InterruptionTest` can you verify if [this PR](https://github.com/dylibso/chicory/pull/731) fixes the issue?

All in all, I'm very supportive of this effort, if you can start to get this exploration in some form in a (possibly Draft) PR we can collaborate on it to bring it to conclusion :pray:

**Comment by yigit** [comment]
yes, that PR seems to have fixed the issue 🥳 

I'll work on creating a PR. I think I can create a generic Gradle project setup that will have the list of `.class` folders that needs to be tested and depends on all of your runtime artifacts.

I'm not sure what is the best way to do a couple of things but i'll pick something and we can iterate. Just listing them here for documentation (and lmk if you have strong opinions that i can follow so it fits your project)

* It will require compiling the maven project and deploying artifacts ahead of time. I'm not sure what is the best way to do it, currently the only way I know is running `mvn deploy -DaltDeploymentRepository=local-repo::default::file:./local-repo -DskipTests`  first. If there is a better way to just build it for a subset, that would be nice.
I can definitely make it a gradle task but it is likely that your CI already does that which we could possibly re-use. 
Also, this is pretty bad for gradle cacheability, but i'm not sure how to avoid it unless your build creates stable jars (e.g. no timestamp on jars etc).

* If all your test classes names are unique (e.g. you are not running them in different configurations), we can probably have just 1 android test project that will run all tests (that will also declare a dependency on all of your artifacts). We could also make it discover all test classes, but I'm guessing not everything has to run on android (e.g. you have plugins). So I think i'll go with an explicit list for now. Or maybe even start small with runtime.

* Running android emulator on github is (or was) quite unstable. On AndroidX, we use an [Firebase Test Lab Runner](https://github.com/androidx/androidx-ci-action) action that handles an extra layer of caching and executes tests on FTL (e.g. it can re-use results if apk contents didn't change). Though, it requires having a firebase project id and GCP project, not sure if you have them. So I'll likely go with the emulator unless you have firebase / GCP accounts that you can use on your CI.

* Probably some more questsions, i'll list them as i discover :)


As for my side project idea, i wanted to run mcp.run on android (so, imagine having ability to deploy AI agents that can run anything from the mcp.run repository and have additional actions that can do stuff on android). I didn't even try and I don't know what it would fully involve. I just happened to find this while reading about it and I thought this would at least be a useful contribution :)

**Comment by torokati44** [comment]
This project over there runs tests on an Android emulator just fine, for reference:
https://github.com/ruffle-rs/ruffle-android/actions/runs/12631450729/job/35193378273

**Comment by yigit** [comment]
Thanks for the heads up. It didn't work well for AndroidX but we have a fairly large project with hours of tests so our requirements might be too much.
I'll try to replicate the setup from your project.

**Comment by andreaTP** [comment]
> I'll work on creating a PR.

:tada: thanks! Happy to help and iterate with you on it!

> - It will require compiling the maven project and deploying artifacts ahead of time. 

That's fine, the atomic Maven command should be something like to: `mvn install -DskipTests -Dmaven.repo.local=./local-repo`.

> this is pretty bad for gradle cacheability,

This is likely to be true, but let start with something that works and make it fast/more efficient later.

> - If all your test classes names are unique 

This assumption doesn't hold unfortunately, at least, `runtime-tests` and `aot-tests` have fully duplicated names.
I'd start with `runtime` only and we sort things out as we go.

> - Running android emulator on github is (or was) quite unstable.

As mentioned, I don't have much experience with Android, but, given @torokati44  feedback( :pray: ), let's start with GH Action.

> - Probably some more questsions, i'll list them as i discover :)

Sure! Feel free to join the Zulip channel to have a chance of more sync chats :+1: 

> As for my side project idea, i wanted to run mcp.run on android

I know @evacchi is backing something in this direction, and @bhelx and @nilslice might be interested in your use case!

> I just happened to find this while reading about it and I thought this would at least be a useful contribution :)

We desperately lack people with Android understanding/experience, it's a super useful contribution :pray: thanks a lot!!!

**Comment by evacchi** [comment]
cool, integrated support for Android integration/instrumentation tests will be very helpful. Internally I managed to run the tests unchanged using the [plug-in you mention above](https://github.com/mannodermaus/android-junit5), but this work to package and run the tests automatically will be very useful.

**Comment by evacchi** [comment]
> As for my side project idea, i wanted to run mcp.run on android 

@yigit I literally [just published a tutorial](https://docs.mcp.run/tutorials/mcpx-gemini-android) for Android support on the mcp.run :D you can find full source code on the [mcpx4j repo](https://github.com/dylibso/mcpx4j/) (which I have also published hours ago!)

**Comment by yigit** [comment]
@evacchi oh nice! I'll take a look at it when i get a chance, ty! Looks like you already have it working what I wanted to try :) But there is always more to try :)

**Comment by illarionov** [comment]
FYI
I reported the issue with `readAllBytes` to the Android team, asking to implement desugaring of this method here: https://issuetracker.google.com/u/1/issues/343482800
Using this method in the Chicory code limits the use on Android to a minAPI of 34.
I think we can ask the Chicory team not to use such methods in order to lower the minimum required api version?

**Comment by yigit** [comment]
I started something here,
https://github.com/yigit/chicory/tree/android-testing

It is a bit more complicated than necessary but I tried to make it as resilient as possible.

New tests from maven modules can be added with [1 line](https://github.com/yigit/chicory/blob/android-testing/android-tests/device-tests/build.gradle.kts#L42):

```kotlin
chicory {
    addTests("runtime") // runtime refers to the runtime folder in the main project.
}
```

I still need to figure out CI and per-test dependencies etc, so there is still work but wanted to share some progress.

**Comment by evacchi** [comment]
@illarionov yes I noticed the min API restriction writing the tutorial above. Have you noticed any other methods that restrict adopting a lower API? If that's the case it shouldn't be a big deal using a utility method instead.

@yigit that's excellent!

**Comment by andreaTP** [comment]
@yigit thanks a lot for your effort, I started taking a look at your changes, and it looks a bit more complicated than I expected.
I understand that there might be complexity that is hard to hide but, parsing POM files and the level of "automagic" configuration seems a bit high from a maintenance point of view.

Let me try to be explicit about the expectation:
- I'm expecting to have a secondary Gradle build, that will use(hard-coded) the source folders from the Maven build
- In this secondary Gradle build 2 things should happen: linting for Android and running the testsuite on emulated Android.

To achieve this goal, if necessary, we can decouple the Maven plugins to be easily invokable in Tasks in the Gradle build, if necessary (just give me a nudge and I can help here). But I'd value an "as simple as possible" Gradle configuration.

**Comment by andreaTP** [comment]
@illarionov I'd like to learn more about your comment.

> `readAllBytes`

There is no problem changing it to a "more compatible" alternative.

> limits the use on Android to a minAPI of 34

Now, let me show all my ignorance about the Android world:
 - what does it mean in practice?
 - is 34 good or should we aim for another level of compatibility?
 - do we have a linter or some automated tool to verify this aspect in CI?
 
 > I think we can ask the Chicory team not to use such methods in order to lower the minimum required api version?
 
That's fine, it would be ideal if we make the changes and guarantee that we don't accidentally break in the future using a CI step.
If the CI is a bigger issue than I imagine, I'm open to accept a PR fixing `readAllBytes` at first and keep the conversation going.

**Comment by evacchi** [comment]
> I'm expecting to have a secondary Gradle build, that will use(hard-coded) the source folders from the Maven build
> [...] running the testsuite on emulated Android

for this specific case, I'd expect locally publishing the test jars could work too; then the gradle build would depend on the the jars; so the flow would be `mvn install`, cd to the gradle build, run the android tests from there

it's possible some linting could be integrated in the Maven build (I am not sure).

**Comment by yigit** [comment]
@andreaTP yep, we are aligned, see the comment on that [last change](https://github.com/yigit/chicory/commit/b08c8c6ee4062b3f9524ea69c561e21eea0d12f0)

> pom parsing. Complexity is not worth the cost so will likely revert but pushing to have in history

I wanted to see how feasible this is but it is unnecessarily complex. I want to make sure you can maintain this if it breaks without me jumping in and also run tests. So, simpler will be better.

Also, more stuff needs to be changed to run more tests. e.g. runtime-tests generate files like this:

```java
testModule0Instance = TestModule.of(
            new File("target/compiled-wast/address/spec.0.wasm"))
          .instantiate(store);
```
which won't work (since device won't have access to the host filesystem). So I wanted to have an idea what exists out there.

I'll likely send a PR that only solves runtime for now. Thanks for checking it.

**Comment by yigit** [comment]
@evacchi for linting, i saw you are using spotless, which does also have a gradle plugin so i was thinking of integrating it to the android project itself.

**Comment by evacchi** [comment]
> which won't work (since device won't have access to the host filesystem). 

@yigit they way I am doing it (on an internal branch for now) is just moving the Wasm binaries to resources, this way you can just load them with the usual `this.getClass().getResourceAsStream(...)` 

I have updated `TestModule.of()` so that the `File` argument is treated as a path to a resource (basically I am stripping the `target/` part, and using `this.getClass()...` etc). This is a hack only to avoid having to change the codegen; come to think of it, for these tests it might be okay to use resources everywhere. 

for linting I was actually thinking the opposite, the runs on a plain JVM so we should be able to have a config for Android run as part of a regular Maven build (maybe behind a flag). This way the Gradle build would be a pure run of the spec tests alone.

**Comment by illarionov** [comment]
@evacchi I think `readBytes` is the only method. Aside from that, the wasi module is implemented using NIO, which requires Andoid API 26. I replaced `readBytes` with my own implementation and tested Chicory on an emulator running Android 8.0 (API 26), and it works fine.

@andreaTP The minimum Android API level supported by a library is an important factor for Android developers when choosing libraries for their applications, as it determines the range of devices on which the integrated code can run.
API level 33 corresponds to Android 13 released on September 2022, which isn’t that old.  
Developers using the Chicory library need to be aware that this part of application will not work on devices that haven’t updated to Android 13. The application will crash if the code execution reaches the `readAllBytes()` on such devices.
API level 26 corresponds to Android 8.0, released on August 2017, supporting of this level makes the library more convenient for developers.

Testing on an emulator with API level 26 should be enough to verify it works and maintain compatibility. The work done here is highly valuable in this context, decisions regarding the minimum supported API level may be addressed at a later time.

If we’re using standard GitHub-hosted runners for testing on the Android emulator, it is also worth noting that these runners have a storage limit of 14 GB, and each Android virtual device takes up to 6–8 GB. If the project requires many other dependencies to build, we could run out of space. In this case, it may be beneficial to separate building the local Maven repository and running instrumented tests into separate jobs.

**Comment by andreaTP** [comment]
Quick check, is anyone involved in this Issue "blocked" or "stuck" on anything?
How can I help to sort things out?

**Comment by yigit** [comment]
sorry for the delay. This week has been very busy at work so I didn't have any energy to work on this. Hopefully i'll get back to it this weekend but lmk if I'm blocking some other plans.

**Comment by andreaTP** [comment]
Thanks for getting back and no worries @yigit !
We don't have any specific timeline, and this is not blocking any other development I'm aware of.

I just wanted to double-check if I was blocking someone 👍 
Take your time and have a great weekend!

**Comment by andreaTP** [comment]
Today I discussed again this issue with @evacchi and the medium term plan is, instead of running the test jars, extracting the `test-gen` logic to a library easily invokable from Gradle, and generate the tests on the fly as we do with Maven, but in a Gradle project.
With this approach we aim to make debugging on Android easier/less painful.

**Comment by evacchi** [comment]
I'll just write it here; at Dylibso we are internally working on an experimental run-time AoT compiler for Android bytecode. In case this sounds interesting, let me know ( I am the one working on it ;) )

**Comment by evacchi** [comment]
I think we can close this for now? :)

**Comment by andreaTP** [comment]
Yes, opened #772 and #773 as follow-ups.
